# vim: ft=dosini
[ids]
*

[main]
capslock = overload(control, esc)
semicolon = lettermod(control, semicolon, 170, 200)
tab = overload(nav, tab)

[nav]
u = capslock
i = home
o = end
p = pageup
h = left
j = down
k = up
l = right
n = pagedown
m = backspace
, = C-left
. = C-right
